// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy27fwzVrCMIkE4oz80EmRO0gRnHOIy1c',
    appId: '1:713209673935:android:1681d565f9582e7b499fba',
    messagingSenderId: '713209673935',
    projectId: 'oneul-fd8ec',
    storageBucket: 'oneul-fd8ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTI-flFIs2zAhGFJY7pJB1SpY02rxb_J8',
    appId: '1:713209673935:ios:76ccd67921ab34e9499fba',
    messagingSenderId: '713209673935',
    projectId: 'oneul-fd8ec',
    storageBucket: 'oneul-fd8ec.appspot.com',
    iosClientId: '713209673935-emqe8g70pqri95hkovbnvtfd5k3vl7tf.apps.googleusercontent.com',
    iosBundleId: 'com.example.whichmenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTI-flFIs2zAhGFJY7pJB1SpY02rxb_J8',
    appId: '1:713209673935:ios:359003242ce2c1f0499fba',
    messagingSenderId: '713209673935',
    projectId: 'oneul-fd8ec',
    storageBucket: 'oneul-fd8ec.appspot.com',
    iosClientId: '713209673935-1egbsc2sfflrqgfv9atecddtobrjkr7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.whichmenu.RunnerTests',
  );
}
